### ISSUE TITLE
Proposal: Please start using Semantic Versioning

### ISSUE THREAD

**Issue by KateGo520** [mathetake/gann#37]
I found that this project already [supports Go modules](https://github.com/mathetake/gann/blob/0.2.0/go.mod). But sadly, the [tags](https://github.com/mathetake/gann/tags) doesn't follow [Semantic Versioning](https://semver.org), which means that all tags of this project will be ignored by Go modules and replaced by pseudo-versions, go get acts weirdly when tags are not in that form. It would be great to have the tagged release be named in the format vX.X.X format so that go mod can read it. 
```
$go get github.com/mathetake/gann@0.2.0
go: downloading github.com/mathetake/gann v0.0.0-20190419042645-f40fe07254d2
go: github.com/mathetake/gann 0.2.0 => v0.0.0-20190419042645-f40fe07254d2
```
Else the mod file shows something like `github.com/mathetake/gann v0.0.0-20190419042645-f40fe07254d2` which is not very readable and difficult to upgrade. It’s hard to verify which version is in use. This is not conducive to version control.

So, I propose this project to follow Semantic Versioning in future versions. For example, `v1.0.1`, `v2.0.0`, `v3.1.0-alpha`, `v3.1.0-beta.2`etc, so that other project can use tag in go.mod.

**Comment by KateGo520** [comment]
@mathetake  Could you help me review this issue? Thx :p

**Comment by mathetake** [comment]
closing since I'm archiving this repo.
